[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# (Opcional) Si usas Functions:
# functions = "netlify/functions"
